deck = ["2club", "2diamond", "2hearts", "2spade", "3club", "3diamond", "3hearts", "3spade",
        "4club", "4diamond", "4hearts", "4spade", "5club", "5diamond", "5hearts", "5spade",
        "6club", "6diamond", "6hearts", "6spade", "7club", "7diamond", "7hearts", "7spade",
        "8club", "8diamond", "8hearts", "8spade", "9club", "9diamond", "9hearts", "9spade",
        "10club", "10diamond", "10hearts", "10spade", "jclub", "jdiamond", "jhearts", "jspade",
        "qclub", "qdiamond", "qhearts", "qspade", "kclub", "kdiamond", "khearts", "kspade",
        "aceclub", "acediamond", "acehearts", "acespade"]

links = {
    "2club": "https://i.ibb.co/gVC0RYY/2club.jpg",
    "2diamond": "https://i.ibb.co/fSLHwfF/2diamond.jpg",
    "2hearts": "https://i.ibb.co/hVwdLsv/2hearts.jpg",
    "2spade": "https://i.ibb.co/99v98rv/2spade.jpg",
    "3club": "https://i.ibb.co/SXk1kFM/3club.jpg",
    "3diamond": "https://i.ibb.co/PDsvkff/3diamond.jpg",
    "3hearts": "https://i.ibb.co/Ry9JLKT/3hearts.jpg",
    "3spade": "https://i.ibb.co/DL1Q0fh/3spade.jpg",
    "4club": "https://i.ibb.co/gDqjQhG/4club.jpg",
    "4diamond": "https://i.ibb.co/8spF4Fr/4diamond.jpg",
    "4hearts": "https://i.ibb.co/r53W626/4hearts.jpg",
    "4spade": "https://i.ibb.co/6gN925C/4spade.jpg",
    "5club": "https://i.ibb.co/4VPqfwD/5club.jpg",
    "5diamond": "https://i.ibb.co/PYgjS6Z/5diamond.jpg",
    "5hearts": "https://i.ibb.co/Ns55fcR/5hearts.jpg",
    "5spade": "https://i.ibb.co/hB9ZhJt/5spade.jpg",
    "6club": "https://i.ibb.co/t3GtH0L/6club.jpg",
    "6diamond": "https://i.ibb.co/XZ8rK62/6diamond.jpg",
    "6hearts": "https://i.ibb.co/TB6sSbR/6hearts.jpg",
    "6spade": "https://i.ibb.co/xCWtMWX/6spade.jpg",
    "7club": "https://i.ibb.co/zFD5TdX/7club.jpg",
    "7diamond": "https://i.ibb.co/k0D4t54/7diamond.jpg",
    "7hearts": "https://i.ibb.co/kBkss1p/7hearts.jpg",
    "7spade": "https://i.ibb.co/2nNx2pt/7spade.jpg",
    "8club": "https://i.ibb.co/R65Km7g/8club.jpg",
    "8diamond": "https://i.ibb.co/ygQDVSp/8diamond.jpg",
    "8hearts": "https://i.ibb.co/XDRGj4H/8hearts.jpg",
    "8spade": "https://i.ibb.co/ch9FfXg/8spade.jpg",
    "9club": "https://i.ibb.co/fkLSnSC/9club.jpg",
    "9diamond": "https://i.ibb.co/PzSYTN5/9diamond.jpg",
    "9hearts": "https://i.ibb.co/qDnxd7Z/9hearts.jpg",
    "9spade": "https://i.ibb.co/whQKm9m/9spade.jpg",
    "10club": "https://i.ibb.co/ky16xdm/10club.jpg",
    "10diamond": "https://i.ibb.co/37dddQn/10diamond.jpg",
    "10hearts": "https://i.ibb.co/cX4zVxn/10hearts.jpg",
    "10spade": "https://i.ibb.co/ydHFV8M/10spade.jpg",
    "jclub": "https://i.ibb.co/12tnjyr/jclub.jpg",
    "jdiamond": "https://i.ibb.co/WfsTPgF/jdiamond.jpg",
    "jhearts": "https://i.ibb.co/tDSyKJN/jhearts.jpg",
    "jspade": "https://i.ibb.co/F7d0cMm/jspade.jpg",
    "qclub": "https://i.ibb.co/bmWN7rD/qclub.jpg",
    "qdiamond": "https://i.ibb.co/n3z1fzs/qdiamond.jpg",
    "qhearts": "https://i.ibb.co/PWxfw9d/qhearts.jpg",
    "qspade": "https://i.ibb.co/K51WbLb/qspade.jpg",
    "kclub": "https://i.ibb.co/mtNsqyK/kclub.jpg",
    "kdiamond": "https://i.ibb.co/2dbkrC0/kdiamond.jpg",
    "khearts": "https://i.ibb.co/rkVXQZk/khearts.jpg",
    "kspade": "https://i.ibb.co/xqy32mk/kspade.jpg",
    "aceclub": "https://i.ibb.co/c2vH2gq/aceclub.jpg",
    "acediamond": "https://i.ibb.co/5k92ymX/acediamond.jpg",
    "acehearts": "https://i.ibb.co/1JKf1dj/acehearts.jpg",
    "acespade": "https://i.ibb.co/Wf13nqD/acespade.jpg",
    "cardback1": "https://i.ibb.co/ZdmDvxQ/cardback.jpg",
    "cardback2": "https://i.ibb.co/DGPb1Qq/cardback2.jpg",
    "cardback3": "https://i.ibb.co/GtWYHrL/cardbackred.png",
    "play_button": "https://i.ibb.co/jwtLDQ8/play-button.png",
    "table": "https://i.ibb.co/sJ963Dc/Table.png"
}


cardbacks = {
    "cardback1": "https://i.ibb.co/ZdmDvxQ/cardback.jpg",
    "cardback2": "https://i.ibb.co/DGPb1Qq/cardback2.jpg",
    "cardback3": "https://i.ibb.co/GtWYHrL/cardbackred.png",
    "cardback4": "https://i.ibb.co/dDY5gm0/antonis-papantoniou-grimoire-cardback.jpg"
}
