version: "3"


services:

  backend:
    image: blackjack_django_backend
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/blackjack_django  # TODO: вот эта строчка отвечает за автообновление после изменения кода?
    ports:
      - "8000:8000"

  nginx:
    image: blackjack_django_nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./static/:/static
